spring.application.name=demo

friendly-captcha.site-key=FCMV9RIFA4K6IUS1
friendly-captcha.api-key=${FRIENDLY_CAPTCHA_API_KEY:A14O674OIKPS39SOL1KI1CUC4IBATGDPH2LFBSNNSDO8F3HVL1HJC533HL}
friendly-captcha.verify-url=https://global.frcapi.com/api/v2/captcha/siteverify

app.proxy.host=proxy.intranet-adsn.fr
app.proxy.port=8080
